Added Visitor Entity
industrycrashcourse/yetanotherecommsite pull request #56
Opened 2021-04-05 08:06 UTC by lkeitadk

I made a new PR because I did a lot of messed up things on the old one and got very lost in what I was doing.

2021-04-06 18:16 UTC, lkeitadk commented
If anybody can see why I'm failing the tests, please let me know

2021-04-06 19:17 UTC, tylerastraub requested changes

2021-04-06 19:17 UTC, tylerastraub commented on ecommerce/src/main/java/com/yetanotheruseless/industrycrashcourse/ecommerce/visitor/Visitor.java
> +    public String getFirstNameName() {
typo

2021-04-06 19:17 UTC, tylerastraub commented on ecommerce/src/main/java/com/yetanotheruseless/industrycrashcourse/ecommerce/visitor/Visitor.java
> +    public void setFirstNameame(String firstName) { this.firstName = firstName; }
another typo (Nameame)

2021-04-06 19:17 UTC, tylerastraub commented on ecommerce/src/main/java/com/yetanotheruseless/industrycrashcourse/ecommerce/visitor/Visitor.java
> +    private List<Product> itemsInCart;
don't need to change this for current PR but the next assignment this could be turned into a shoppingCart

2021-04-06 19:17 UTC, tylerastraub commented on ecommerce/src/main/java/com/yetanotheruseless/industrycrashcourse/ecommerce/visitor/VisitorController.java
> +        if (visitor.getFirstNameName() == null) {}
for future PR this line should either do something or be removed

2021-04-06 19:17 UTC, tylerastraub commented on ecommerce/src/test/java/com/yetanotheruseless/industrycrashcourse/ecommerce/EcommerceApiTests.java
> +    }
i am confused - did you change this test? if it was already passing and you did not write it, not sure why it would be changed

2021-04-06 19:17 UTC, tylerastraub commented on ecommerce/src/test/java/com/yetanotheruseless/industrycrashcourse/ecommerce/EcommerceApiTests.java
> +    private VisitorService visitorService;
this might be why tests are failing, there is no @MockBean listed above the service like there is for ProductService

2021-04-06 19:25 UTC, lkeitadk commented on ecommerce/src/test/java/com/yetanotheruseless/industrycrashcourse/ecommerce/EcommerceApiTests.java
> +    }
Nice catch, I don't remember why I did this

2021-04-06 20:05 UTC, lkeitadk commented on ecommerce/src/test/java/com/yetanotheruseless/industrycrashcourse/ecommerce/EcommerceApiTests.java
> +    private VisitorService visitorService;
It was indeed. Tried it on linux and the build was finally succesful. I jsut need to update it with main and it should be fine. Thank you

2021-04-07 20:55 UTC, tylerastraub approved these changes

2021-04-07 23:37 UTC, jakemannix commented on ecommerce/src/main/java/com/yetanotheruseless/industrycrashcourse/ecommerce/visitor/Visitor.java
> +    private List<Product> itemsInCart;
agreed.  next PR, switch from a list of Products to a single ShoppingCart (maybe an Optional<ShoppingCart>?)

2021-04-07 23:39 UTC, jakemannix commented on ecommerce/src/main/java/com/yetanotheruseless/industrycrashcourse/ecommerce/visitor/VisitorController.java
> +        if (visitor.getFirstName() == null) {System.out.println("Does Not Exist");}
instead of System.out.println, we should perhaps throw an exception here (one which leads to a HTTP 400 error)

2021-04-07 23:45 UTC, jakemannix approved these changes
looks good to go!

2021-04-08 03:01 UTC, merged